### ISSUE TITLE
Couldn't run the download script

### ISSUE THREAD

**Issue by chenming-wu** [MattWallingford/360-1M#1]
Hi! Thanks for the great work and dataset. However, it seems like there is no way to run the provided scripts for data crawling. 

Could you please check if the provided script can be run?

Thanks

**Comment by chenming-wu** [comment]
Also, would it be possible to provide the estimated poses as part of the dataset as well? Thanks!

**Comment by MattWallingford** [comment]
Hi Chenming,

We provided a script for local downloading in DownloadVideos/download_local.py. You may have been experiencing issues with the other script because it's built to download videos to a GCP bucket. You can download the videos to your local machine with the command ```DownloadVideos/download_local.py --in_path 360-1M.parquet --out_dir /path/to/videos```. We will also be providing the poses and a smaller high-quality subset in a week or so since it's difficult for many to download such a large amount of video.
